### ISSUE TITLE
Add BOM for Mouser projects to KiBot output

### ISSUE THREAD

**Issue by Kampi** [Kampi/BeeLight#31]
```
  - name: "BOM for Mouser"
    comment: "BOM for the Mouser BOM-Tool"
    type: bom
    dir: docs
    category: "purchasing"
    options:
      format: XLSX
      count_smd_tht: true
      output: "BOM_Mouser.%x"
      ref_separator: ','
      columns:
        - field: manf#
          name: Manufacturer Part Number
        - field: mouser#
          name: Mouser Part Number
        - field: manf#
          name: Manufacturer Name
        - field: Value
          name: Description
        - field: Build Quantity
          name: Quantity
      xlsx:
        kicost: false
        specs: false
        title: "%f BOM"
        hide_stats_info: true
        hide_pcb_info: true
        logo: false
        col_colors: false
        style: "classic"
        title: ""
```
